# -*- coding: utf-8 -*-
"""machine_learning_exemplo_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gxrKn5L-AT2WMWE1e8no9vZnTya2hpwE
"""

import matplotlib

from sklearn.datasets import make_regression
x, y = make_regression(n_samples=250, n_features=1, noise=40)
import matplotlib.pyplot as plt

plt.scatter(x,y)
plt.show()